import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyzeTransaction } from '../src/analyze.js';
import { systemTransferFixture, tokenTransferCheckedFixture, setAuthorityFixture, unknownProgramFixture, malformedFixture } from '../fixtures/builders.js';

const basePolicy = { maxSolSpendLamports:'100000000', maxTokenAmountRaw:'1000000', unknownProgram:'REVIEW', authorityChange:'BLOCK' };

test('AT-01 small allowed SOL transfer -> ALLOW', async()=>{const f=systemTransferFixture(50_000_000n);const r=await analyzeTransaction({base64Transaction:f.base64,policy:{...basePolicy,requireRecipientAllowlist:true,recipientAllowlist:[f.destination]}});assert.equal(r.decision,'ALLOW');assert.equal(r.instructions[0].destination,f.destination);});
test('AT-02 SOL transfer above cap -> BLOCK', async()=>{const f=systemTransferFixture(150_000_000n);const r=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});assert.equal(r.decision,'BLOCK');assert.ok(r.reasons.some(x=>x.code==='SOL_SPEND_CAP_EXCEEDED'));});
test('AT-03 token transfer above cap -> BLOCK', async()=>{const f=tokenTransferCheckedFixture(2_000_000n);const r=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});assert.equal(r.decision,'BLOCK');assert.ok(r.reasons.some(x=>x.code==='TOKEN_SPEND_CAP_EXCEEDED'));});
test('AT-04 non-allowlisted recipient -> BLOCK', async()=>{const f=systemTransferFixture(1n);const r=await analyzeTransaction({base64Transaction:f.base64,policy:{...basePolicy,requireRecipientAllowlist:true,recipientAllowlist:[]}});assert.equal(r.decision,'BLOCK');assert.ok(r.reasons.some(x=>x.code==='RECIPIENT_NOT_ALLOWLISTED'));});
test('AT-05 token SetAuthority -> BLOCK', async()=>{const r=await analyzeTransaction({base64Transaction:setAuthorityFixture().base64,policy:basePolicy});assert.equal(r.decision,'BLOCK');assert.ok(r.reasons.some(x=>x.code==='AUTHORITY_CHANGE_INSTRUCTION'));});
test('AT-06 unknown program never silently allows', async()=>{const r=await analyzeTransaction({base64Transaction:unknownProgramFixture().base64,policy:basePolicy});assert.notEqual(r.decision,'ALLOW');assert.ok(r.reasons.some(x=>x.code==='UNKNOWN_PROGRAM'));});
test('AT-07 simulation error -> BLOCK', async()=>{const f=systemTransferFixture(1n);const {parseTransactionBase64}=await import('../src/transaction.js');const {decodeInstructions}=await import('../src/decoders.js');const {evaluatePolicy}=await import('../src/policy.js');const p=parseTransactionBase64(f.base64);const d=decodeInstructions(p);const e=evaluatePolicy(p,d,{status:'error',error:'fixture failure'},basePolicy);assert.equal(e.decision,'BLOCK');assert.ok(e.reasons.some(x=>x.code==='SIMULATION_FAILED'));});
test('AT-08 malformed transaction -> structured BLOCK', async()=>{const r=await analyzeTransaction({base64Transaction:malformedFixture(),policy:basePolicy});assert.equal(r.decision,'BLOCK');assert.equal(r.reasons[0].code,'MALFORMED_OR_UNSUPPORTED_TRANSACTION');});
test('AT-09 deterministic decision/reasons', async()=>{const f=unknownProgramFixture();const a=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});const b=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});assert.deepEqual(a,b);});
test('AT-10 evidence includes required audit fields', async()=>{const f=systemTransferFixture(1n);const r=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});assert.match(r.transaction.fingerprintSha256,/^[0-9a-f]{64}$/);assert.ok(Array.isArray(r.transaction.staticAccountKeys));assert.ok(Array.isArray(r.instructions));assert.equal(r.policy.policyVersion,'1.0');assert.ok('decision' in r);assert.ok('reasons' in r);});
test('AT-11 application source contains no signing/broadcast/private-key workflow',()=>{const here=path.dirname(fileURLToPath(import.meta.url));const src=path.join(here,'..','src');const cli=path.join(here,'..','cli.js');const text=fs.readdirSync(src).filter(n=>n.endsWith('.js')).map(n=>fs.readFileSync(path.join(src,n),'utf8')).join('\n')+fs.readFileSync(cli,'utf8');for(const forbidden of ['sendTransaction','signTransaction','secretKey','Keypair.fromSecretKey','wallet.connect'])assert.equal(text.includes(forbidden),false,forbidden);});
test('AT-12 version-0 static-key transfer parses and allows', async()=>{const f=systemTransferFixture(10n,0);const r=await analyzeTransaction({base64Transaction:f.base64,policy:basePolicy});assert.equal(r.transaction.version,0);assert.equal(r.decision,'ALLOW');});
